# This file contains config for a baremetal deployment
#
# SSH connection options include:
#
# * host - the remote server hostname/IP
# * port - defaults to 22
# * username - required, the user you're connecting as
# * password - only set if you're not using key-based authentication
# * privateKey - local file path to a private key that will be sent with the connection request
# * passphrase - used if your private key has a passphrase
# * agentForward - set to `true` to forward the client machine's ssh credentials
#
# See https://redwoodjs.com/docs/deploy/baremetal for more info

[[production.servers]]
host = "64.227.125.242"
username = "redwood"
privateKey = "/home/rassul/.ssh/id_ed25519"
agentForward = false
sides = ["api", "web"]
path = "/var/www/rwblog"
processNames = ["api"]
repo = "git@github.com:rtabulov/redwoodblog.git"
branch = "main"
keepReleases = 3
packageManagerCommand = "yarn"
monitorCommand = "pm2"

# If you have separate api and web servers:
#
# [[production.servers]]
# host = "api.server.com"
# user = "user"
# agentForward = true
# sides = ["api"]
# path = "/var/www/app"
# repo = "git@github.com:redwoodjs/redwood.git"
# branch = "main"
# processNames = ["api"]
#
# [[production.servers]]
# host = "web.server.com"
# user = "user"
# agentForward = true
# sides = ["web"]
# path = "/var/www/app"
# repo = "git@github.com:redwoodjs/redwood.git"
# branch = "main"
# migrate = false # only one server in a cluster needs to migrate
# processNames = ["web"]
