version: '3.1'

services:

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5454:5432"
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: c18042mz43xkmRyLPwPG
